"""Topic modeling from scratch — collapsed-Gibbs LDA, multiplicative-update NMF, and coherence.

This is the single source of truth for the chapter: the concept page, the teaching notebook, and
the figure generator (`make_figures_15.py`) all import the functions and constants defined here, so
none of them can silently drift from the others. Every headline number on the page is produced by
this file.

What it contains:
  * `make_planted_corpus`     -- a tiny synthetic corpus with KNOWN ("planted") topics, so we can
                                 check that LDA/NMF *recover* the truth, not just produce something.
  * `GibbsLDA`                -- collapsed Gibbs sampling for LDA, from scratch (Griffiths & Steyvers
                                 2004). The conditional that reassigns a word's topic is the heart
                                 of the page's math.
  * `nmf_multiplicative`      -- NMF by Lee & Seung's multiplicative updates, from scratch, on the
                                 same corpus, with a scikit-learn cross-check.
  * `npmi_coherence` /        -- topic coherence from scratch (NPMI and UMass), used to show a
    `umass_coherence`           coherent topic scores far above a random word set.
  * `READABLE_CORPUS` + the   -- the 18-document sports/cooking/space corpus the page's bar chart
    sklearn helpers             and `theta` demo are measured on, fit with scikit-learn.

Determinism: everything stochastic is driven by an explicit integer seed through a local
`np.random.Generator` (never the global RNG, never Python's `hash()`), so the same seed yields
bit-for-bit identical topics on any machine. Any string -> id mapping uses a STABLE md5 hash, not
Python's salted `hash()`. Pure NumPy + scikit-learn, CPU only.

Run:
    python topic_modeling.py
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

import numpy as np

# --- Global seed used everywhere on the page, in the notebook, and in the figures --------------
SEED: int = 7

# --- The planted synthetic corpus -------------------------------------------------------------
# Three disjoint vocabularies, one per planted topic. A document is generated by picking a dominant
# topic and drawing most of its words from that topic's bag plus a few "leak" words from others --
# exactly the admixture LDA assumes. Because we KNOW the planting, we can verify recovery.
PLANTED_TOPIC_WORDS: tuple[tuple[str, ...], ...] = (
    ("goal", "team", "match", "league", "striker", "coach"),       # topic 0: SPORTS
    ("garlic", "onion", "tomato", "recipe", "bake", "simmer"),      # topic 1: COOKING
    ("orbit", "planet", "rocket", "galaxy", "telescope", "moon"),   # topic 2: SPACE
)
PLANTED_TOPIC_NAMES: tuple[str, ...] = ("sports", "cooking", "space")

N_PLANTED_DOCS: int = 60          # documents in the synthetic corpus
PLANTED_DOC_LEN: int = 40         # words per synthetic document
PLANTED_LEAK: float = 0.15        # fraction of a doc's words drawn from OTHER topics (admixture)

# --- The human-readable corpus the scikit-learn demo + bar chart are measured on ---------------
# 18 short documents, 6 per theme. Counts -> LDA, TF-IDF -> NMF (the two correct representations).
READABLE_CORPUS: tuple[str, ...] = (
    "the team won the football game with a last minute goal by the striker",
    "the coach praised the players after the team match victory on the field",
    "fans cheered as the team scored another goal to win the football league",
    "the player passed the ball and the team scored the winning championship goal",
    "the striker and the goalkeeper battled as the football team chased the goal",
    "the league champions celebrated the victory after the players won the match",
    "the recipe needs fresh garlic onion tomato basil and a pinch of salt",
    "bake the bread dough in the oven and add butter sugar and flour",
    "chop the onion fry the garlic and simmer the tomato sauce with basil slowly",
    "the cake recipe uses sugar flour butter eggs and a cup of milk",
    "stir the soup add salt onion garlic and let the sauce simmer in the pot",
    "knead the dough whisk the eggs and bake the cake until the bread is golden",
    "the rocket launched into orbit carrying a satellite for the space mission",
    "astronauts aboard the station observed the planet and the distant stars",
    "the spacecraft reached orbit and the telescope captured the distant galaxy",
    "the space mission sent a probe past the moon toward the outer planet",
    "the satellite orbited the planet while astronauts studied the stars and galaxy",
    "the telescope and the spacecraft tracked the rocket toward the moon",
)

# Priors used by the from-scratch Gibbs sampler and the scikit-learn LDA on the readable corpus.
ALPHA: float = 0.1     # doc-topic prior: < 1 -> each document is about few topics (sparse theta)
ETA: float = 0.01      # topic-word prior: < 1 -> each topic is about few words (sparse, crisp beta)


def stable_token_id(token: str, vocab_size: int) -> int:
    """Map a token to a stable bucket via md5 (NOT Python's salted hash()).

    Used only where a deterministic, run-independent string->int is needed; the corpus builders
    below assign ids by sorted vocabulary order, which is also stable. md5 is here so any auxiliary
    hashing on the page is reproducible across processes and machines.
    """
    digest = hashlib.md5(token.encode("utf-8")).hexdigest()
    return int(digest, 16) % vocab_size


def make_planted_corpus(
    *,
    seed: int = SEED,
    n_docs: int = N_PLANTED_DOCS,
    doc_len: int = PLANTED_DOC_LEN,
    leak: float = PLANTED_LEAK,
) -> tuple[list[list[int]], list[str], np.ndarray]:
    """Generate a synthetic corpus with KNOWN topics so recovery can be checked.

    Each document is assigned one dominant planted topic; `(1 - leak)` of its words are drawn from
    that topic's word bag and `leak` from the union of the other topics. Returns:
      docs      -- list of documents, each a list of integer token ids (the bag, order irrelevant)
      vocab     -- id -> token (sorted union of all planted topic words)
      true_topic_of_doc -- the planted dominant topic per document (ground truth, for evaluation)
    """
    rng = np.random.default_rng(seed)
    vocab = sorted({w for words in PLANTED_TOPIC_WORDS for w in words})
    token_to_id = {w: i for i, w in enumerate(vocab)}
    topic_word_ids = [[token_to_id[w] for w in words] for words in PLANTED_TOPIC_WORDS]
    n_topics = len(PLANTED_TOPIC_WORDS)

    docs: list[list[int]] = []
    true_topic_of_doc = np.empty(n_docs, dtype=np.int64)
    for d in range(n_docs):
        dominant = d % n_topics  # balanced: equal documents per planted topic
        true_topic_of_doc[d] = dominant
        others = [k for k in range(n_topics) if k != dominant]
        doc: list[int] = []
        for _ in range(doc_len):
            if rng.random() < leak:
                src = others[rng.integers(len(others))]  # a leak word from a different topic
            else:
                src = dominant                            # a word from the document's own topic
            doc.append(int(rng.choice(topic_word_ids[src])))
        docs.append(doc)
    return docs, vocab, true_topic_of_doc


def docs_to_count_matrix(docs: list[list[int]], vocab_size: int) -> np.ndarray:
    """Bag-of-words count matrix (n_docs x vocab_size) from integer-id documents."""
    counts = np.zeros((len(docs), vocab_size), dtype=np.float64)
    for d, doc in enumerate(docs):
        for w in doc:
            counts[d, w] += 1.0
    return counts


# ============================================================================================
# Collapsed Gibbs sampling for LDA (Griffiths & Steyvers 2004)
# ============================================================================================
@dataclass
class GibbsLDA:
    """Collapsed Gibbs sampler for Latent Dirichlet Allocation, from scratch.

    The state is the topic assignment z for every word occurrence, plus the running count tables
    n_dk (doc x topic), n_kw (topic x word) and n_k (topic). One sweep visits every word, removes
    it from the counts, samples a new topic from the collapsed conditional

        p(z_i = k | rest)  proportional to  (n_dk[d,k] + alpha) * (n_kw[k,w] + eta) / (n_k[k] + V*eta)

    and adds it back. After burn-in the counts give the estimated topic-word (phi) and doc-topic
    (theta) distributions. This is the exact update derived on the page.
    """

    n_topics: int
    alpha: float = ALPHA
    eta: float = ETA
    n_iter: int = 300
    seed: int = SEED

    def log_likelihood(self, docs: list[list[int]], vocab_size: int) -> float:
        """Corpus log-likelihood log p(w | z) under the current assignment, marginalizing phi/theta.

        Uses the predictive distributions implied by the current counts. Rises as the sampler
        organizes the corpus, which is what the convergence figure plots.
        """
        phi = self.topic_word()
        theta = self.doc_topic()
        ll = 0.0
        for d, doc in enumerate(docs):
            # P(w | d) = sum_k theta[d,k] phi[k,w]; sum log over the document's words
            pw = theta[d] @ phi[:, doc]  # (len(doc),)
            ll += float(np.log(pw + 1e-12).sum())
        return ll

    def fit(self, docs: list[list[int]], vocab_size: int) -> "GibbsLDA":
        rng = np.random.default_rng(self.seed)
        K, V = self.n_topics, vocab_size
        D = len(docs)

        # Count tables and the per-occurrence assignment list.
        self.n_dk = np.zeros((D, K), dtype=np.float64)
        self.n_kw = np.zeros((K, V), dtype=np.float64)
        self.n_k = np.zeros(K, dtype=np.float64)
        self.assignments: list[np.ndarray] = []

        # --- random initialization: every word gets a random topic ---
        for d, doc in enumerate(docs):
            z_d = rng.integers(0, K, size=len(doc))
            self.assignments.append(z_d)
            for i, w in enumerate(doc):
                k = z_d[i]
                self.n_dk[d, k] += 1.0
                self.n_kw[k, w] += 1.0
                self.n_k[k] += 1.0

        # --- Gibbs sweeps ---
        for _ in range(self.n_iter):
            for d, doc in enumerate(docs):
                z_d = self.assignments[d]
                for i, w in enumerate(doc):
                    k_old = z_d[i]
                    # remove word i from the counts (the "leave-one-out" n^{-i})
                    self.n_dk[d, k_old] -= 1.0
                    self.n_kw[k_old, w] -= 1.0
                    self.n_k[k_old] -= 1.0
                    # the collapsed conditional, term by term as on the page
                    left = self.n_dk[d] + self.alpha                 # doc already likes topic k
                    right = (self.n_kw[:, w] + self.eta) / (self.n_k + V * self.eta)  # topic likes w
                    p = left * right
                    p /= p.sum()
                    k_new = rng.choice(K, p=p)
                    # add it back under the new topic
                    z_d[i] = k_new
                    self.n_dk[d, k_new] += 1.0
                    self.n_kw[k_new, w] += 1.0
                    self.n_k[k_new] += 1.0
        return self

    def fit_with_trace(
        self, docs: list[list[int]], vocab_size: int, true_topic_of_doc: np.ndarray
    ) -> tuple[list[int], list[float], list[float]]:
        """Like fit(), but record (iteration, log-likelihood, purity) each sweep for the convergence
        figure. Reinitializes state and runs the same updates as fit()."""
        rng = np.random.default_rng(self.seed)
        K, V = self.n_topics, vocab_size
        D = len(docs)
        self.n_dk = np.zeros((D, K))
        self.n_kw = np.zeros((K, V))
        self.n_k = np.zeros(K)
        self.assignments = []
        for d, doc in enumerate(docs):
            z_d = rng.integers(0, K, size=len(doc))
            self.assignments.append(z_d)
            for i, w in enumerate(doc):
                self.n_dk[d, z_d[i]] += 1.0
                self.n_kw[z_d[i], w] += 1.0
                self.n_k[z_d[i]] += 1.0

        iters, lls, purities = [], [], []
        for it in range(self.n_iter):
            for d, doc in enumerate(docs):
                z_d = self.assignments[d]
                for i, w in enumerate(doc):
                    k_old = z_d[i]
                    self.n_dk[d, k_old] -= 1.0
                    self.n_kw[k_old, w] -= 1.0
                    self.n_k[k_old] -= 1.0
                    p = (self.n_dk[d] + self.alpha) * (self.n_kw[:, w] + self.eta) / (self.n_k + V * self.eta)
                    p /= p.sum()
                    k_new = rng.choice(K, p=p)
                    z_d[i] = k_new
                    self.n_dk[d, k_new] += 1.0
                    self.n_kw[k_new, w] += 1.0
                    self.n_k[k_new] += 1.0
            if it % 5 == 0 or it == self.n_iter - 1:
                pred = self.doc_topic().argmax(axis=1)
                iters.append(it)
                lls.append(self.log_likelihood(docs, V))
                purities.append(purity(true_topic_of_doc, pred, K))
        return iters, lls, purities

    def topic_word(self) -> np.ndarray:
        """phi[k, w] = P(word w | topic k), smoothed by eta (rows sum to 1)."""
        phi = self.n_kw + self.eta
        return phi / phi.sum(axis=1, keepdims=True)

    def doc_topic(self) -> np.ndarray:
        """theta[d, k] = P(topic k | doc d), smoothed by alpha (rows sum to 1)."""
        theta = self.n_dk + self.alpha
        return theta / theta.sum(axis=1, keepdims=True)

    def top_words(self, vocab: list[str], n: int = 6) -> list[list[str]]:
        """Top-n words per topic, by phi — what a human reads to name the topic."""
        phi = self.topic_word()
        return [[vocab[i] for i in row.argsort()[::-1][:n]] for row in phi]


# ============================================================================================
# NMF by multiplicative updates (Lee & Seung 1999/2001)
# ============================================================================================
def nmf_multiplicative(
    X: np.ndarray,
    n_topics: int,
    *,
    n_iter: int = 400,
    seed: int = SEED,
    eps: float = 1e-9,
) -> tuple[np.ndarray, np.ndarray, list[float]]:
    """Factor X (>= 0) as W @ H with W, H >= 0, by Lee & Seung's multiplicative updates.

        H <- H * (W^T X) / (W^T W H)        W <- W * (X H^T) / (W H H^T)

    Both updates are ratios of non-negative quantities, so non-negativity is preserved with no
    clipping. Returns W (docs x topics), H (topics x words), and the per-iteration Frobenius error
    so the monotone decrease can be plotted. `eps` guards against division by zero.
    """
    rng = np.random.default_rng(seed)
    n_docs, n_words = X.shape
    # non-negative random init, scaled to the data so the first error is sane
    scale = np.sqrt(X.mean() / n_topics) if X.mean() > 0 else 1.0
    W = rng.random((n_docs, n_topics)) * scale
    H = rng.random((n_topics, n_words)) * scale

    errors: list[float] = [float(np.linalg.norm(X - W @ H))]
    for _ in range(n_iter):
        H = H * (W.T @ X) / (W.T @ W @ H + eps)
        W = W * (X @ H.T) / (W @ H @ H.T + eps)
        errors.append(float(np.linalg.norm(X - W @ H)))
    return W, H, errors


def nmf_top_words(H: np.ndarray, vocab: list[str], n: int = 6) -> list[list[str]]:
    """Top-n words per topic from an NMF H factor (topics x words)."""
    return [[vocab[i] for i in row.argsort()[::-1][:n]] for row in H]


# The tiny 3x3 example traced by hand on the page (Example 3). Fixed init so the page numbers are
# exactly reproducible -- this is the single source of those numbers.
NMF_EXAMPLE_V = np.array([[5.0, 4.0, 0.0], [0.0, 1.0, 4.0], [4.0, 3.0, 1.0]])
NMF_EXAMPLE_W0 = np.array([[0.30, 0.98], [0.13, 0.77], [0.52, 0.66]])
NMF_EXAMPLE_H0 = np.array([[0.24, 0.30, 0.90], [1.07, 0.41, 0.79]])


def nmf_example_trace(n_steps: int = 6, eps: float = 1e-9) -> dict:
    """Run the by-hand 3x3 NMF example from the fixed init and return the numbers the page quotes:
    the first updated rows H1[0], W1[0], and the full Frobenius-error trajectory."""
    V, W, H = NMF_EXAMPLE_V, NMF_EXAMPLE_W0.copy(), NMF_EXAMPLE_H0.copy()
    errors = [float(np.linalg.norm(V - W @ H))]
    first = {}
    for step in range(n_steps):
        H = H * (W.T @ V) / (W.T @ W @ H + eps)
        W = W * (V @ H.T) / (W @ H @ H.T + eps)
        if step == 0:
            first = {"H1_row0": np.round(H[0], 3).tolist(), "W1_row0": np.round(W[0], 3).tolist()}
        errors.append(float(np.linalg.norm(V - W @ H)))
    return {"errors": [round(e, 2) for e in errors], **first}


# ============================================================================================
# Topic coherence, from scratch (NPMI and UMass)
# ============================================================================================
def _word_doc_frequency(counts: np.ndarray) -> np.ndarray:
    """Per word, the number of documents containing it (document frequency)."""
    return (counts > 0).sum(axis=0).astype(np.float64)


def _word_cooccurrence(counts: np.ndarray) -> np.ndarray:
    """Co-document-frequency matrix: entry (i, j) = #docs containing BOTH word i and word j."""
    present = (counts > 0).astype(np.float64)
    return present.T @ present


def npmi_coherence(word_ids: list[int], counts: np.ndarray, *, eps: float = 1e-12) -> float:
    """Mean pairwise NPMI of a word set, computed over the corpus's document co-occurrence.

    For each pair (i, j):
        PMI  = log[ P(i, j) / (P(i) P(j)) ],   NPMI = PMI / -log P(i, j)
    with P estimated by document frequency / n_docs. NPMI in [-1, 1]; higher = the words co-occur
    more than chance = a more coherent topic. A coherent topic scores well above a random word set.
    """
    n_docs = counts.shape[0]
    df = _word_doc_frequency(counts)
    co = _word_cooccurrence(counts)
    p = df / n_docs
    scores: list[float] = []
    for a in range(len(word_ids)):
        for b in range(a + 1, len(word_ids)):
            i, j = word_ids[a], word_ids[b]
            p_ij = co[i, j] / n_docs
            if p_ij <= 0:
                scores.append(-1.0)  # never co-occur -> maximally incoherent pair
                continue
            pmi = np.log(p_ij / (p[i] * p[j] + eps) + eps)
            npmi = pmi / (-np.log(p_ij + eps))
            scores.append(float(npmi))
    return float(np.mean(scores)) if scores else 0.0


def umass_coherence(word_ids: list[int], counts: np.ndarray, *, eps: float = 1.0) -> float:
    """A numerically-stabilized, pair-AVERAGED variant of UMass coherence (Mimno et al. 2011).

    The canonical UMass score is the *sum* over ordered top-word pairs of
        log[ (D(w_i, w_j) + 1) / D(w_j) ]
    with D(w_j) the document frequency of w_j and D(w_i, w_j) the co-document-frequency. This
    implementation makes two deliberate, documented changes so the score is comparable across word
    sets of different sizes and never divides by zero:
      * smoothing `eps` (default 1.0) is added to BOTH numerator and denominator -> log[(co+eps)/(df+eps)];
      * the pair scores are AVERAGED (divided by the pair count), not summed.
    Words are assumed passed most-probable first. Less negative (higher) = more coherent. The
    page's formula and prose state this exact stabilized, averaged form.
    """
    df = _word_doc_frequency(counts)
    co = _word_cooccurrence(counts)
    total = 0.0
    pairs = 0
    for a in range(1, len(word_ids)):
        for b in range(a):  # j < i: condition the higher-ranked word on the lower-ranked one
            i, j = word_ids[a], word_ids[b]
            total += float(np.log((co[i, j] + eps) / (df[j] + eps)))
            pairs += 1
    return total / pairs if pairs else 0.0


# ============================================================================================
# scikit-learn end-to-end on the readable corpus (LDA on counts, NMF on TF-IDF)
# ============================================================================================
def sweep_k_coherence_perplexity(
    counts: np.ndarray, k_values: tuple[int, ...] = (2, 3, 4, 5, 6, 8)
) -> tuple[list[int], list[float], list[float]]:
    """For each K, fit scikit-learn LDA on a train split of `counts` and return (K, mean UMass
    coherence on the train counts, held-out perplexity on a test split).

    Run on the *planted* corpus (a clean 3-theme count matrix), where the signal is strong enough
    that held-out perplexity is minimized and coherence peaks at the true K = 3 — the figure that
    motivates "sweep K, pick the elbow". On tiny readable corpora the test split is too small for a
    stable perplexity, which is exactly why we sweep on the larger synthetic corpus. scikit-learn
    imported lazily."""
    from sklearn.decomposition import LatentDirichletAllocation

    n = counts.shape[0]
    rng = np.random.default_rng(SEED)
    perm = rng.permutation(n)
    n_train = int(0.7 * n)
    X_train, X_test = counts[perm[:n_train]], counts[perm[n_train:]]

    ks, coherences, perplexities = [], [], []
    for k in k_values:
        lda = LatentDirichletAllocation(
            n_components=k, random_state=SEED, max_iter=200, learning_method="batch",
            doc_topic_prior=ALPHA, topic_word_prior=ETA,
        ).fit(X_train)
        topic_coh = [umass_coherence(list(row.argsort()[::-1][:6]), X_train) for row in lda.components_]
        ks.append(k)
        coherences.append(float(np.mean(topic_coh)))
        perplexities.append(float(lda.perplexity(X_test)))
    return ks, coherences, perplexities


def sklearn_lda_nmf(corpus: tuple[str, ...], n_topics: int = 3, top_n: int = 6):
    """Fit scikit-learn LDA (on counts) and NMF (on TF-IDF) and return their top words + doc-0 theta.

    Imported lazily so the from-scratch parts of this module work without scikit-learn installed.
    Returns (lda_topics, nmf_topics, doc0_theta) where each *_topics is a list of word lists.
    """
    from sklearn.decomposition import NMF, LatentDirichletAllocation
    from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

    def _top(components, vocab):
        return [[vocab[i] for i in row.argsort()[::-1][:top_n]] for row in components]

    cv = CountVectorizer(stop_words="english", min_df=1)
    X_counts = cv.fit_transform(corpus)
    lda = LatentDirichletAllocation(
        n_components=n_topics, random_state=3, max_iter=200, learning_method="batch",
        doc_topic_prior=ALPHA, topic_word_prior=ETA,
    ).fit(X_counts)
    lda_topics = _top(lda.components_, cv.get_feature_names_out())
    doc0_theta = lda.transform(X_counts[0])[0]

    tf = TfidfVectorizer(stop_words="english", min_df=1)
    X_tfidf = tf.fit_transform(corpus)
    nmf = NMF(n_components=n_topics, random_state=0, init="nndsvda", max_iter=400).fit(X_tfidf)
    nmf_topics = _top(nmf.components_, tf.get_feature_names_out())

    return lda_topics, nmf_topics, doc0_theta


def purity(true_topic_of_doc: np.ndarray, pred_topic_of_doc: np.ndarray, n_topics: int) -> float:
    """Cluster purity: for each predicted topic, the fraction of its docs in the majority true topic,
    averaged with cluster sizes. Topic numbering is arbitrary, so purity (not accuracy) measures
    whether the discovered grouping MATCHES the planted one regardless of label permutation."""
    total = len(true_topic_of_doc)
    correct = 0
    for k in range(n_topics):
        members = true_topic_of_doc[pred_topic_of_doc == k]
        if members.size == 0:
            continue
        correct += int(np.bincount(members, minlength=n_topics).max())
    return correct / total


def main() -> None:
    """Print every headline number on the page: planted-topic recovery, NMF, and coherence."""
    print("device: cpu (pure-Python / numpy + scikit-learn)")
    print("numpy:", np.__version__)
    try:
        import torch

        print("torch:", torch.__version__)
    except ImportError:
        print("torch: not importable (not needed — this chapter is NumPy + scikit-learn)")
    print(f"seed: {SEED}\n")

    # --- 1. Planted corpus + from-scratch Gibbs LDA ---
    docs, vocab, true_topic = make_planted_corpus()
    V = len(vocab)
    counts = docs_to_count_matrix(docs, V)
    print(f"planted corpus: {len(docs)} docs, |V|={V}, doc_len={PLANTED_DOC_LEN}, leak={PLANTED_LEAK}")

    lda = GibbsLDA(n_topics=3, n_iter=300, seed=SEED).fit(docs, V)
    print("\nGibbs-LDA recovered topics (top words):")
    for k, words in enumerate(lda.top_words(vocab, n=6)):
        print(f"  topic {k}: {', '.join(words)}")

    pred = lda.doc_topic().argmax(axis=1)
    pur = purity(true_topic, pred, 3)
    print(f"\ndoc-topic purity vs planted truth: {pur:.3f}")
    assert pur >= 0.95, "Gibbs LDA failed to recover the planted topics"

    # --- 2. From-scratch NMF on the same corpus ---
    W, H, errors = nmf_multiplicative(counts, n_topics=3, n_iter=400, seed=SEED)
    print("\nNMF (multiplicative updates) recovered topics (top words):")
    for k, words in enumerate(nmf_top_words(H, vocab, n=6)):
        print(f"  topic {k}: {', '.join(words)}")
    print(f"\nNMF Frobenius error: {errors[0]:.2f} -> {errors[-1]:.2f} (monotone decrease)")
    assert errors[-1] < errors[0], "NMF error should decrease"
    assert all(errors[i + 1] <= errors[i] + 1e-6 for i in range(len(errors) - 1)), "NMF must be monotone"

    # --- 3. Coherence: a coherent topic beats a random word set ---
    coherent = [vocab.index(w) for w in PLANTED_TOPIC_WORDS[0]]  # a real planted topic
    rng = np.random.default_rng(SEED)
    random_set = list(rng.choice(V, size=len(coherent), replace=False))
    c_npmi = npmi_coherence(coherent, counts)
    r_npmi = npmi_coherence(random_set, counts)
    c_umass = umass_coherence(coherent, counts)
    r_umass = umass_coherence(random_set, counts)
    print("\ncoherence — coherent (planted) topic vs random word set:")
    print(f"  NPMI : coherent {c_npmi:+.3f}  vs  random {r_npmi:+.3f}")
    print(f"  UMass: coherent {c_umass:+.3f}  vs  random {r_umass:+.3f}")
    assert c_npmi > r_npmi, "a coherent topic must out-score a random set on NPMI"
    assert c_umass > r_umass, "a coherent topic must out-score a random set on UMass"

    # --- 4. scikit-learn end-to-end on the readable corpus ---
    lda_topics, nmf_topics, theta0 = sklearn_lda_nmf(READABLE_CORPUS, n_topics=3)
    print("\nscikit-learn on the 18-doc readable corpus:")
    print("  LDA topics (counts):")
    for k, words in enumerate(lda_topics):
        print(f"    topic {k}: {', '.join(words)}")
    print("  NMF topics (TF-IDF):")
    for k, words in enumerate(nmf_topics):
        print(f"    topic {k}: {', '.join(words)}")
    print(f"  doc-0 topic mixture (theta): {np.round(theta0, 3)}")
    assert theta0.max() > 0.9, "doc-0 (a match report) should be dominated by one topic"
    print("\nall asserts passed.")


if __name__ == "__main__":
    main()
